# Generated by Django 4.2.16 on 2024-11-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_analysisform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisForm',
        ),
    ]
