# Generated by Django 5.1.3 on 2024-11-25 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='highlight',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
