# Generated by Django 5.1.3 on 2024-11-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_annotation_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='highlight',
        ),
    ]
