# Generated by Django 5.1.3 on 2024-11-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_annotation_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='highlight',
            field=models.TextField(default=''),
        ),
    ]
