# Generated by Django 5.1.3 on 2024-11-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_annotation_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='relevancy',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low')], default='low', max_length=10),
        ),
    ]
